### ISSUE TITLE
Service veticles failing to re-register to zk on zk restart 

### ISSUE THREAD

**Issue by AnveshMora** [vert-x3/vertx-zookeeper#152]
### Questions

We have infra running on AWS ECS, zookeper is running on Docker, same as other servies.

During regular service usage in production, zookeeper intermittently restarts. During that time we are seeing vert.x service verticles are failing to re-register with new zookeeper instance

### Version

Which version(s) did you encounter this bug ?
Java: 17
vertex-core: 4.4.6
vertex-zookeeper: 4.4.2

### Context

I encountered an exception which looks suspicious while zookeper restarts:
`
[vert.x-eventloop-thread-2] WARN  i.v.core.eventbus.impl.clustered.ConnectionHolder - Connecting to server a3369c02-695f-4f23-ba11-711027489f8d failed (?:?)  io.vertx.core.VertxException: Not a member of the cluster at io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager.lambda$null$9(ZookeeperClusterManager.java:250) at java.base/java.util.Optional.orElseThrow(Unknown Source) at io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager.lambda$getNodeInfo$10(ZookeeperClusterManager.java:250) at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180) at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277) at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199) at datadog.trace.bootstrap.instrumentation.java.concurrent.Wrapper.run(Wrapper.java:46) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Unknown Source)
`

### Do you have a reproducer?
Nope

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

Link to github project/gist

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. Having zookeeper setup on docker
2. Having one or services registering to event-bus
3. restart the zookeeper, than we see above error message.

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by AnveshMora** [comment]
Similar issue raised by me on vert-x3 issues repo: https://github.com/vert-x3/issues/issues/651

**Comment by AnveshMora** [comment]
Hi everyone, just wanted to check if any of the community had similar issue has above or any suggestions how to tackle this issue?

**Comment by AnveshMora** [comment]
Any insights/ guidance to resolve this issue?

**Comment by AnveshMora** [comment]
Hi @vietj , We have resolved this issue in-house. I'm planning on opening PR to the issue which will allow the services auto-register with ZK.

**Comment by AnveshMora** [comment]
Raised a PR, Please review and let me know any comments on the PR. 

thanks

**Comment by chipnesh** [comment]
Try upgrading the curator library to version 5.9.0.
This version fixes an issue related to refreshing the IP address associated with a ZooKeeper server instance’s domain name.

Also, make sure that your ZooKeeper instances are **not** hosted behind a single domain name using round-robin DNS.
Each instance should have its own domain name and be listed in `zookeeperHosts`, separated by commas.

This:
```json
"zookeeperHosts": "my-zookeeper-0.my-zookeeper-headless.default.svc.cluster.local,my-zookeeper-1.my-zookeeper-headless.default.svc.cluster.local,my-zookeeper-2.my-zookeeper-headless.default.svc.cluster.local"
```

Instead of this:

```json
"zookeeperHosts": "my-zookeeper.my-zookeeper-headless.default.svc.cluster.local"
```
