### ISSUE TITLE
Can't store Buffer in shared data

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-zookeeper#49]
It's not possible to store Buffer in the shared data at the moment:

```
java.lang.IllegalStateException: Failed to load class Class io.vertx.spi.cluster.zookeeper.impl.ZKMap can not access a member of class io.vertx.core.buffer.impl.BufferImpl with modifiers ""
	at io.vertx.spi.cluster.zookeeper.impl.ZKMap.asObject(ZKMap.java:121)
	at io.vertx.spi.cluster.zookeeper.impl.ZKAsyncMap.lambda$get$2(ZKAsyncMap.java:70)
	at io.vertx.core.Future.lambda$compose$1(Future.java:270)
```

`BufferImpl` has no public constructor, meaning that to create a new instance you must call `setAccessible(true)`.

**Comment by stream1984** [comment]
OK, i will fix it up.

**Comment by stream1984** [comment]
close by [PR](https://github.com/vert-x3/vertx-zookeeper/pull/50)
