### ISSUE TITLE
EOFException on readBoolean

### ISSUE THREAD

**Issue by MarWestermann** [vert-x3/vertx-zookeeper#58]
Hi,
I deployed two vertx applications to openshift clustered by zookeeper.
In both instances I get a lot of exceptions like:

`

[Curator-TreeCache-0] ERROR org.apache.curator.framework.recipes.cache.TreeCache -
--
  | java.io.EOFException
  | at java.io.DataInputStream.readBoolean(DataInputStream.java:244)
  | at io.vertx.spi.cluster.zookeeper.impl.ZKMap.asObject(ZKMap.java:110)
  | at io.vertx.spi.cluster.zookeeper.impl.ZKAsyncMultiMap$Listener.childEvent(ZKAsyncMultiMap.java:270)
  | at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:741)
  | at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:735)
  | at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
  | at org.apache.curator.shaded.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
  | at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
  | at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:734)
  | at org.apache.curator.framework.recipes.cache.TreeCache.access$1700(TreeCache.java:71)
  | at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:852)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)

`

vertx.version: 3.4.2
zookeeper: https://github.com/redhat-reactive-msa/zookeeper/ (v. 3.4.6)

**Comment by jg513** [comment]
I got the exception too, how to solve it?

**Comment by jg513** [comment]
A) not throw the exception:
```java
    vertx.eventBus().consumer("consumer-1");
```

B) throw the exception:
```java
    vertx.eventBus().consumer("consumer/1");
```

B will create a node `1` under `consumer`, and the data is a byte array of zero length.
