### ISSUE TITLE
KeeperErrorCode = NoNode issue after upgrading to 3.6.0

### ISSUE THREAD

**Issue by yaoligang** [vert-x3/vertx-zookeeper#73]
I have upgraded vertx-zookeeper from 3.5.4 to 3.6.0 and found the following issue if it is connected to a clean Zookeeper server. If the zookeeper server been used before, this issue will not be reported.

```
SEVERE: Failed to join cluster
io.vertx.core.VertxException: io.vertx.core.VertxException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /io.vertx/syncMap/__vertx.haInfo
	at io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager.addLocalNodeID(ZookeeperClusterManager.java:271)
	at io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager.lambda$join$7(ZookeeperClusterManager.java:334)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.vertx.core.VertxException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /io.vertx/syncMap/__vertx.haInfo
	at io.vertx.spi.cluster.zookeeper.impl.ZKSyncMap.clear(ZKSyncMap.java:140)
	at io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager.createThisNode(ZookeeperClusterManager.java:279)
	at io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager.addLocalNodeID(ZookeeperClusterManager.java:268)
	... 7 more
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /io.vertx/syncMap/__vertx.haInfo
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:250)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:244)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:241)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:225)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
	at io.vertx.spi.cluster.zookeeper.impl.ZKSyncMap.clear(ZKSyncMap.java:137)
	... 9 more
```

**Comment by vietj** [comment]
@tsegismont I think it's related to the fixes we made for clustering

**Comment by yaoligang** [comment]
It can be solved by manually create "/io.vertx/syncMap/__vertx.haInfo" node in the zookeeper server before connecting with vertx-zookeeper.

**Comment by HY3798** [comment]
May I know how did you resolve this issue I am getting 
KeeperErrorCode = NoNode for /io.vertex/syncMap/__vertx.haInfo

**Comment by naveenjeeri** [comment]
what's the resolution for this, even though I am on vertex 3.8.5 I am still seeing this issue.
