### ISSUE TITLE
exception on shutdown of a clustered vertx instance

### ISSUE THREAD

**Issue by radai-rosenblatt** [vert-x3/vertx-zookeeper#87]
im constructing a simple zookeper-backed clustered vertx, like so:
```java
VertxOptions options = new VertxOptions();
ClusterManager clusterManager = new ZookeeperClusterManager(zkConfig);
options.setClusterManager(clusterManager);
EventBusOptions eventBusOptions = options.getEventBusOptions();
eventBusOptions.setClustered(true);
Vertx.clusteredVertx(options, ...);
```
seems to work fine, but when i shut it down, i get this:
```
Jul 17, 2019 9:27:31 AM io.vertx.core.eventbus.impl.clustered.ClusteredEventBus
SEVERE: Failed to remove sub
java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:367)
	at io.vertx.spi.cluster.zookeeper.impl.ZKMap.lambda$checkExists$5(ZKMap.java:198)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:749)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:522)
	at org.apache.curator.framework.imps.SyncBuilderImpl$1.processResult(SyncBuilderImpl.java:108)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:637)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)
```

**Comment by stream1984** [comment]
Hi radai
That is a flaw on vertx-zookeeper, i did not check Curator Client State while Curator have closed with zookeeper, and i have no way to tell the Vertx that Client is break with Server.
I will try to fix such flaw in Vertx4 by checking state of Curator.

**Comment by radai-rosenblatt** [comment]
@stream1984 - are there builds of vertx-zk 4.* that i can try somewhere? also (in my opinion) curator's dependency on unreleased "beta" versions of ZK makes it unfit for production use - have you considered using the "raw" zk client ?

**Comment by stream1984** [comment]
@radai-rosenblatt 
you can try to update version `<curator.version>2.12.0</curator.version>` in your branch, and i will also upgrade curator to the 4.x in next month with Vert.x4.
You could exclude version of ZK-beta and include ZK-3.5.5 in your pom.
well, using raw zk-client would make more code for some trivia code, i have no enough time to do that, maybe you could provide some help :)

**Comment by radai-rosenblatt** [comment]
latest curator "scares" me because my workplace doesnt run zk 3.5 in production - i dont know of any org that does. they claim to be runtime compatible with 3.4, but ....
